services:
  linkding:
    image: sissbruecker/linkding:latest
    container_name: linkding
    ports:
      - "8282:9090"
    volumes:
      - linkding-data:/etc/linkding/data
    environment:
      - LD_SUPERUSER_NAME=${LD_SUPERUSER_NAME}
      - LD_SUPERUSER_PASSWORD=${LD_SUPERUSER_PASSWORD}
      - TZ=${TZ}
    restart: unless-stopped

volumes:
  linkding-data:
