name: home_metrics_dbt

profile: home_metrics_dbt

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  home_metrics_dbt:
    +schema: raw

models:
  home_metrics_dbt:
    # Default schema for any layer not overridden below (marts, etc.)
    +schema: mart
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
      +schema: staging
      +meta:
        hidden: true
    intmdt:
      +materialized: table
      +schema: intmdt
      +meta:
        hidden: true
    dim:
      +materialized: table
    fct:
      +materialized: table
    marts:
      +materialized: table
